# Generated by Django 3.1.3 on 2021-03-17 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='email',
            new_name='employee_email',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='employee_name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='username',
            new_name='employee_phone',
        ),
        migrations.RemoveField(
            model_name='task',
            name='phone',
        ),
    ]
